spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpashop?serverTimezone=UTC
    username: root
    password: 8011
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug
 #   org.hibernate.type: trace # parameter 값 보기

decorator:
  datasource:
    # p6spy 설정 적용
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j